globalThis.assert(Object.is(globalThis.addon.toBool(true), true))
globalThis.assert(Object.is(globalThis.addon.toBool(1), true))
globalThis.assert(Object.is(globalThis.addon.toBool(-1), true))
globalThis.assert(Object.is(globalThis.addon.toBool('true'), true))
globalThis.assert(Object.is(globalThis.addon.toBool('false'), true))
globalThis.assert(Object.is(globalThis.addon.toBool({}), true))
globalThis.assert(Object.is(globalThis.addon.toBool([]), true))
globalThis.assert(Object.is(globalThis.addon.toBool(false), false))
globalThis.assert(Object.is(globalThis.addon.toBool(undefined), false))
globalThis.assert(Object.is(globalThis.addon.toBool(null), false))
globalThis.assert(Object.is(globalThis.addon.toBool(0), false))
globalThis.assert(Object.is(globalThis.addon.toBool(Number.NaN), false))
globalThis.assert(Object.is(globalThis.addon.toBool(''), false))

globalThis.assert(Object.is(globalThis.addon.toNumber(0), 0))
globalThis.assert(Object.is(globalThis.addon.toNumber(1), 1))
globalThis.assert(Object.is(globalThis.addon.toNumber(1.1), 1.1))
globalThis.assert(Object.is(globalThis.addon.toNumber(-1), -1))
globalThis.assert(Object.is(globalThis.addon.toNumber('0'), 0))
globalThis.assert(Object.is(globalThis.addon.toNumber('1'), 1))
globalThis.assert(Object.is(globalThis.addon.toNumber('1.1'), 1.1))
globalThis.assert(Object.is(globalThis.addon.toNumber([]), 0))
globalThis.assert(Object.is(globalThis.addon.toNumber(false), 0))
globalThis.assert(Object.is(globalThis.addon.toNumber(null), 0))
globalThis.assert(Object.is(globalThis.addon.toNumber(''), 0))
globalThis.assert(Number.isNaN(globalThis.addon.toNumber(Number.NaN)))
globalThis.assert(Number.isNaN(globalThis.addon.toNumber({})))
globalThis.assert(Number.isNaN(globalThis.addon.toNumber(undefined)))

globalThis.assert(Object.is(globalThis.addon.toString(''), ''))
globalThis.assert(Object.is(globalThis.addon.toString('globalThis.addon'), 'globalThis.addon'))
globalThis.assert(Object.is(globalThis.addon.toString(undefined), 'undefined'))
globalThis.assert(Object.is(globalThis.addon.toString(null), 'null'))
globalThis.assert(Object.is(globalThis.addon.toString(false), 'false'))
globalThis.assert(Object.is(globalThis.addon.toString(true), 'true'))
globalThis.assert(Object.is(globalThis.addon.toString(0), '0'))
globalThis.assert(Object.is(globalThis.addon.toString(1.1), '1.1'))
globalThis.assert(Object.is(globalThis.addon.toString(Number.NaN), 'NaN'))
globalThis.assert(Object.is(globalThis.addon.toString({}), '[object Object]'))
globalThis.assert(Object.is(globalThis.addon.toString({ toString: () => 'globalThis.addon' }), 'globalThis.addon'))
globalThis.assert(Object.is(globalThis.addon.toString([]), ''))
globalThis.assert(Object.is(globalThis.addon.toString([1, 2, 3]), '1,2,3'))

export { }